version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: maniknp/php:1.4-php8.2-alpine
    container_name: app-php 
    volumes:
      - ./data:/var/www/
    # depends_on:
    #   - db
      
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: online_exam
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/init:/docker-entrypoint-initdb.d
  #     - ./mysql/backup:/backup
  #   ports:
  #     - "3306:3306"
