version: '4'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./data:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp-cli
      
  wp-cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: maniknp/wp-cli:1.1-php8.2-alpine
    container_name: wp-cli-php
    volumes:
      - ./data:/var/www/
      - ./docker-entrypoint.d:/docker-entrypoint.d
    # depends_on:
    #   - db
      
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: online_exam
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/init:/docker-entrypoint-initdb.d
  #     - ./mysql/backup:/backup
  #   ports:
  #     - "3306:3306"
